name: flutter_stetho_example
description: Demonstrates how to use the flutter_stetho plugin.

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_stetho:
    path: ../

flutter:
  uses-material-design: true
